### PR TITLE
Development

### PR DESCRIPTION
**Pull request by rvvergara**
Hi Kevin. This is our latest project. Please note that we didn't do any tests (except probably just the user model test but that was just in the beginning). The reason is that we wanted to focus on the building of the app (we'll just start testing again with the next project). 

The general specs for this app (per https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations):
"A user can create events. A user can attend many events. An event can be attended by many users. This will require you to model many-to-many relationships and also to be very conscious about your foreign keys and class names (hint: you won’t be able to just rely on Rails’ defaults like you have before)."

We just added a little bit more. Thanks for your review, in advance.

Dipto and Ryan

### CODE REVIEW

**Comment by talihomz** [comment]
Hi @rvvergara @dipto0321 

I love the simple UI on this project, very well done! I was able to load the app, create a user, sign in, create an event and view the same event. Well done guys! (Couldn't edit my profile though)

Here are my thoughts on the code:
1. In the events controller, the [current implementation](https://github.com/rvvergara/private-events/blob/cb144a1380cce987df641261095df0c7ccd6fbbd/app/controllers/events_controller.rb#L20) uses `new` to create the event. Best practice would be to use `build` instead, which would add the event, but not save it until you explicitly save it. You can have a look at this [tutorial](https://www.sitepoint.com/brush-up-your-knowledge-of-rails-associations/) for some explanation on the same.

2. I didn't get to see the `invites` feature for each event. Was it implemented in this?

3. In your [database schemas](https://github.com/talihomz/FakeBook/blob/develop/db/schema.rb), where are the foreign keys? The indexes are ok, but we are missing foreign keys here. Foreign keys are [extensively covered](https://guides.rubyonrails.org/association_basics.html) in the tutorials, you can have a look at them to find out what you possibly left out.

This was abit bigger than the previous project, and I have a feeling we will iterate a couple of times until we get it done. Great work so far though!

**Comment by rvvergara** [comment]
Hi Kevin,

Thanks for your review of our project. Please check out my replies below for each point:

> Hi @rvvergara @dipto0321
> 
> I love the simple UI on this project, very well done! I was able to load the app, create a user, sign in, create an event and view the same event. Well done guys! (Couldn't edit my profile though)
> 
> Here are my thoughts on the code:
> 
>     1. In the events controller, the [current implementation](https://github.com/rvvergara/private-events/blob/cb144a1380cce987df641261095df0c7ccd6fbbd/app/controllers/events_controller.rb#L20) uses `new` to create the event. Best practice would be to use `build` instead, which would add the event, but not save it until you explicitly save it. You can have a look at this [tutorial](https://www.sitepoint.com/brush-up-your-knowledge-of-rails-associations/) for some explanation on the same.
_Reply: Refactored the new action in the events_controller to reflect this suggested change. Yeah that's the better way to do it :)_

> 
>     2. I didn't get to see the `invites` feature for each event. Was it implemented in this?
>     _Reply: It's a bonus feature so we didn't implement this one. Though yeah, it would be a great additional feature:)_
>     3. In your [database schemas](https://github.com/talihomz/FakeBook/blob/develop/db/schema.rb), where are the foreign keys? The indexes are ok, but we are missing foreign keys here. Foreign keys are [extensively covered](https://guides.rubyonrails.org/association_basics.html) in the tutorials, you can have a look at them to find out what you possibly left out.
Reply: Already changed the creator
> 
> 
> This was abit bigger than the previous project, and I have a feeling we will iterate a couple of times until we get it done. Great work so far though!

**Comment by rvvergara** [comment]
Hi Kevin,

Thanks for your review of our project. Please check out my replies below for each point:

> Hi @rvvergara @dipto0321
> 
> I love the simple UI on this project, very well done! I was able to load the app, create a user, sign in, create an event and view the same event. Well done guys! (Couldn't edit my profile though)
> 
> Here are my thoughts on the code:
> 
>     1. In the events controller, the [current implementation](https://github.com/rvvergara/private-events/blob/cb144a1380cce987df641261095df0c7ccd6fbbd/app/controllers/events_controller.rb#L20) uses `new` to create the event. Best practice would be to use `build` instead, which would add the event, but not save it until you explicitly save it. You can have a look at this [tutorial](https://www.sitepoint.com/brush-up-your-knowledge-of-rails-associations/) for some explanation on the same.
_Reply: Refactored the new action in the events_controller to reflect this suggested change. Yeah that's the better way to do it :)_

> 
>     2. I didn't get to see the `invites` feature for each event. Was it implemented in this?
>     _Reply: It's a bonus feature so we didn't implement this one. Though yeah, it would be a great additional feature:)_
>     3. In your [database schemas](https://github.com/talihomz/FakeBook/blob/develop/db/schema.rb), where are the foreign keys? The indexes are ok, but we are missing foreign keys here. Foreign keys are [extensively covered](https://guides.rubyonrails.org/association_basics.html) in the tutorials, you can have a look at them to find out what you possibly left out.
_Reply: Already added a foreign_key constraint to creator_id column in events. :)_
> 
> 
> This was abit bigger than the previous project, and I have a feeling we will iterate a couple of times until we get it done. Great work so far though!

**Comment by talihomz** [comment]
@rvvergara @dipto0321 

There is one Foreign key missing: `event -> attendances`. Foreign keys will help you ensure integrity between these entities and so, as a rule, wherever two separate tuples have a relation, you should add a foreign key.

Great job so far!

**Comment by rvvergara** [comment]
Thanks Kevin! I created a new branch (in order to implement the invitation feature). And in this branch I added foreign key constraints for both attendances and events tables. I intended on making a pull request of this to the dev branch but the views themselves aren't done yet and I'm still having some issues with 3 examples in feature test (you will also find them in the feature tests when you run them). Here's the link to that branch: 

https://github.com/rvvergara/private-events/tree/invitation-model

**Comment by talihomz** [comment]
@rvvergara @dipto0321 

Aah, ok. This might make you guys take longer to satisfy the minimum requirements for this project though. If you feel comfortable taking your time understanding these concepts, go ahead and when you are done, push to this branch so that we have all changes recorded under this pull request.

**Comment by talihomz** [comment]
👍

**Pull request merged**
